### ISSUE TITLE
Create connection between Postgresql Database and Graphql-Api with Prisma.

### ISSUE THREAD

**Issue by mfeyziodabas** [galip16/ya_tutarsa#13]
- [ ] Create one functional prisma example from databank to local development environment.

**Comment by galip16** [comment]
I guess this is done with this [commit](https://github.com/galip16/ya_tutarsa/commit/e0b93c0fcc9c98526657e63c0a6cc3fcfd80d2f1)

We can close this issue or? @mfeyziodabas

**Comment by mfeyziodabas** [comment]
Does your solution have database connection too?
@galip16

**Comment by galip16** [comment]
> Does your solution have database connection too? @galip16

yep

**Comment by mfeyziodabas** [comment]
Of course then, close it firmly. And take care of yourself.
